import { test, expect } from '@playwright/test'

test('staff selection, transactions, review and sign-off survive a new session',async({page,context})=>{
  await page.goto('/')
  await page.getByLabel('Username',{exact:true}).fill('admin')
  await page.getByLabel('Password',{exact:true}).fill('local-integration-test-password')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeVisible()
  await expect(page.locator('fieldset')).toBeEnabled()
  await page.locator('input[type=file]').setInputFiles('public/examples/sample-transactions.csv')
  await expect(page.getByText('Changes saved.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Monthly Upload',exact:true}).click()
  await page.getByLabel('Choose an investor to add as staff').selectOption('Sample Staff Member')
  await expect(page.getByRole('button',{name:'Remove Sample Staff Member from staff'})).toBeVisible()
  await page.getByRole('button',{name:'Staff Investment',exact:true}).click()
  await expect(page.locator('tbody')).toContainText('Sample Staff Member')
  await expect(page.locator('tfoot')).toContainText('1,000.00')
  await page.getByRole('button',{name:/Review Queue/}).click()
  await page.getByRole('combobox',{name:'Decision',exact:true}).selectOption('Cleared')
  await expect(page.getByLabel('Reviewed by',{exact:true})).toHaveValue('Admin')
  await page.getByLabel('Compliance comments',{exact:true}).fill('Verified source of funds')
  await page.getByRole('button',{name:'Save Review',exact:true}).click()
  await expect(page.getByText('Changes saved.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Reports & Sign-Off',exact:true}).click()
  await expect(page.getByLabel('Reviewed by',{exact:true})).toHaveValue('Admin')
  await page.getByLabel('Designation',{exact:true}).fill('Compliance Officer')
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('Completed')
  await page.getByRole('button',{name:'Save Sign-Off',exact:true}).click()
  await expect(page.getByText('Changes saved.',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.locator('fieldset')).toBeEnabled()
  await expect(page.getByText('3',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Reports & Sign-Off',exact:true}).click()
  await expect(page.getByLabel('Reviewed by',{exact:true})).toHaveValue('Admin')
  await expect(page.getByRole('combobox',{name:'Status',exact:true})).toHaveValue('Completed')
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  await expect(page.getByLabel('Password',{exact:true})).toBeVisible()
  expect((await context.request.get('/api/datasets')).status()).toBe(401)
  await page.getByLabel('Username',{exact:true}).fill('admin')
  await page.getByLabel('Password',{exact:true}).fill('local-integration-test-password')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.locator('fieldset')).toBeEnabled()
  await page.getByRole('button',{name:'Monthly Upload',exact:true}).click()
  await expect(page.getByRole('button',{name:'Remove Sample Staff Member from staff'})).toBeVisible()
  await page.getByRole('button',{name:'Remove Sample Staff Member from staff'}).click()
  await expect(page.getByText('No staff selected yet.',{exact:false})).toBeVisible()
  await page.reload()
  await expect(page.locator('fieldset')).toBeEnabled()
  await page.getByRole('button',{name:'Monthly Upload',exact:true}).click()
  await expect(page.getByText('No staff selected yet.',{exact:false})).toBeVisible()
})

test('D1 imports are isolated, validated and protected from stale writes',async({request})=>{
  const headers={Origin:'http://127.0.0.1:8788'}
  expect((await request.get('/api/datasets')).status()).toBe(401)
  expect((await request.post('/api/login',{headers,data:{username:'admin',password:'wrong'}})).status()).toBe(401)
  expect((await request.post('/api/login',{headers,data:{username:'admin',password:'local-integration-test-password'}})).status()).toBe(200)
  expect((await request.post('/api/imports',{headers:{Origin:'https://other.example'},data:{}})).status()).toBe(403)
  expect((await request.get('/api/unknown')).status()).toBe(404)
  const start=async(dataset:string,version:string,count:number)=>{
    const response=await request.post('/api/imports',{headers,data:{dataset,version,count,source:'test'}})
    expect(response.status()).toBe(200);return (await response.json()).id as string
  }
  const put=(id:string,items:unknown[],offset=0)=>request.put(`/api/imports/${id}`,{headers,data:{items,offset}})
  const commit=(id:string)=>request.post(`/api/imports/${id}/commit`,{headers,data:{}})
  const read=(version:string)=>request.get(`/api/records?dataset=notes&version=${version}&offset=0`)
  const note={noteId:'1',referenceId:'REF-1',noteName:'First note'}
  const first=await start('notes','',1)
  expect((await put(first,[{noteId:''}])).status()).toBe(400)
  expect((await commit(first)).status()).toBe(400)
  expect((await put(first,[note])).status()).toBe(200)
  expect((await commit(first)).status()).toBe(200)
  const second=await start('notes',first,2)
  await put(second,[{...note,noteName:'New name'}])
  expect((await commit(second)).status()).toBe(400)
  expect(await (await read(first)).json()).toEqual([note])
  await put(second,[{...note,noteId:'2'}],1)
  expect((await commit(second)).status()).toBe(200)
  const stale=await start('notes',first,1)
  await put(stale,[note])
  expect((await commit(stale)).status()).toBe(409)
  expect((await (await read(second)).json()).length).toBe(2)
  // A committed revision remains immutable for paginated readers.
  expect((await put(second,[note])).status()).toBe(404)
  const rules=await start('rules','',1)
  await put(rules,[{id:'TM-001',name:'Mandatory',description:'Test',enabled:false,locked:false,threshold:1}])
  await commit(rules)
  const stored=await (await request.get(`/api/records?dataset=rules&version=${rules}`)).json()
  expect(stored[0]).toMatchObject({enabled:true,locked:true,threshold:30000})
})

test('reimporting one month resets its conclusions and preserves other months',async({request})=>{
  const headers={Origin:'http://127.0.0.1:8788'}
  await request.post('/api/login',{headers,data:{username:'admin',password:'local-integration-test-password'}})
  async function save(dataset:string,version:string,items:unknown[]){
    const started=await request.post('/api/imports',{headers,data:{dataset,version,source:'monthly.csv',count:items.length}})
    expect(started.status()).toBe(200)
    const {id}=await started.json()
    expect((await request.put(`/api/imports/${id}`,{headers,data:{offset:0,items}})).status()).toBe(200)
    const committed=await request.post(`/api/imports/${id}/commit`,{headers,data:{}})
    expect(committed.status()).toBe(200)
    return id as string
  }
  const before=await (await request.get('/api/datasets')).json()
  const september=before.find((d:{name:string})=>d.name==='transactions:2026-09')
  const transaction={sourceRow:2,noteId:'',name:'October Investor',userType:'Investor',bank:'',accountNo:'',amount:31000,transactionNo:'',dateRaw:'2026-10-01',date:'2026-10-01T04:00:00.000Z',payVia:'',action:'Deposit'}
  const first=await save('transactions:2026-10','',[transaction])
  const flagId='2026-10|name:octoberinvestor|TM-001'
  await save(`review:${flagId}`,'',[{flagId,decision:'Cleared',comments:'Checked',reviewedBy:'Tester',reviewedAt:new Date().toISOString()}])
  await save('signoff:2026-10','',[{month:'2026-10',reviewedBy:'Tester',designation:'Officer',comments:'Done',status:'Completed',updatedAt:new Date().toISOString()}])
  await save('transactions:2026-10',first,[{...transaction,amount:45000}])
  const after=await (await request.get('/api/datasets')).json()
  expect(after.some((d:{name:string})=>d.name===`review:${flagId}`)).toBe(false)
  expect(after.some((d:{name:string})=>d.name==='signoff:2026-10')).toBe(false)
  expect(after.find((d:{name:string})=>d.name==='transactions:2026-09')).toEqual(september)
  expect((await request.post('/api/imports',{headers,data:{padding:'x'.repeat(1_000_001)}})).status()).toBe(413)
})

test('temporary password change revokes sessions and compliance permissions are enforced',async({page,request})=>{
  const headers={Origin:'http://127.0.0.1:8788'}
  const login=await request.post('/api/login',{headers,data:{username:'compliance',password:'local-integration-test-password'}})
  expect(login.status()).toBe(200)
  expect((await login.json()).user).toMatchObject({role:'compliance',mustChangePassword:true})
  expect((await request.get('/api/datasets')).status()).toBe(403)
  await page.goto('/')
  await page.getByLabel('Username',{exact:true}).fill('compliance')
  await page.getByLabel('Password',{exact:true}).fill('local-integration-test-password')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Change password',exact:true})).toBeVisible()
  await page.getByLabel('Current password',{exact:true}).fill('local-integration-test-password')
  await page.getByLabel('New password',{exact:true}).fill('compliance-new-test-password')
  await page.getByLabel('Confirm new password',{exact:true}).fill('compliance-new-test-password')
  await page.getByRole('button',{name:'Save password',exact:true}).click()
  await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible()
  expect((await request.get('/api/me')).status()).toBe(401)
  expect((await request.post('/api/login',{headers,data:{username:'compliance',password:'local-integration-test-password'}})).status()).toBe(401)
  await page.getByLabel('Username',{exact:true}).fill('compliance')
  await page.getByLabel('Password',{exact:true}).fill('compliance-new-test-password')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.locator('fieldset').first()).toBeEnabled()
  await page.getByRole('button',{name:'Monitoring Rules',exact:true}).click()
  await expect(page.getByRole('button',{name:'Save Rules',exact:true})).toBeDisabled()
  for(const dataset of ['rules','signoff:2026-10']){
    expect((await page.request.post('/api/imports',{headers,data:{dataset,version:'',source:'',count:1}})).status()).toBe(403)
  }
  const flagId='2026-10|name:octoberinvestor|TM-001'
  const created=await page.request.post('/api/imports',{headers,data:{dataset:`review:${flagId}`,version:'',source:'',count:1}})
  expect(created.status()).toBe(200)
  const {id}=await created.json()
  await page.request.put(`/api/imports/${id}`,{headers,data:{offset:0,items:[{flagId,decision:'Cleared',comments:'Reviewed',reviewedBy:'Spoofed Admin',reviewedAt:new Date().toISOString()}]}})
  expect((await page.request.post(`/api/imports/${id}/commit`,{headers,data:{}})).status()).toBe(200)
  const stored=await (await page.request.get(`/api/records?dataset=${encodeURIComponent(`review:${flagId}`)}&version=${id}`)).json()
  expect(stored[0].reviewedBy).toBe('Compliance Officer')
  expect((await request.post('/api/login',{headers,data:{username:'chiefcompliance',password:'local-integration-test-password'}})).status()).toBe(200)
  const chief=await request.post('/api/imports',{headers,data:{dataset:'signoff:2026-10',version:'',source:'',count:1}})
  expect(chief.status()).toBe(200)
  // A user cannot finish another user's staged import, even with a privileged role.
  const {id:chiefJob}=await chief.json()
  expect((await page.request.post(`/api/imports/${chiefJob}/commit`,{headers,data:{}})).status()).toBe(404)
})
